indent = 2
margin = 68
format_markdown = true
verbose = true
always_for_in = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
pipe_to_function_call = true
always_use_return = true
whitespace_in_kwargs = false
format_docstrings = true
conditional_to_if = true
trailing_comma = true
