project:
  type: book
  output-dir: docs

book:
  title: "Embrace Uncertainty"
  subtitle: "Mixed-effects models with Julia"
  author: 
    - name: Phillip Alday
      email: me@phillipalday.com
      orcid: 0000-0002-9984-5745
      affiliation:
        - name: Beacon Biosignals
          url: https://beacon.bio
    - name: Reinhold Kliegl
      email: reinhold.kliegl@gmail.com
      orcid: 0000-0002-0180-8488
      affiliation:
        - name: University of Potsdam
          city: Potsdam
          country: Germany
          url: https://uni-potsdam.de
    - name: Douglas Bates
      email: dmbates@gmail.com
      orcid: 0000-0001-8316-9503
      affiliation:
        - name: University of Wisconsin - Madison
          city: Madison
          state: WI
          url: https://www.wisc.edu
          department: Statistics
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - multiple.qmd
    - longitudinal.qmd
    - largescaledesigned.qmd
    - largescaleobserved.qmd
    - glmmbernoulli.qmd
    - references.qmd
  appendices:
    - datatables.qmd
    - linalg.qmd
    - aGHQ.qmd

execute-dir: project

bibliography: references.bib
csl: apa-annotated-bibliography.csl

github:
  owner: JuliaMixedModels
  repo: EmbraceUncertainty

resources:
  - CNAME
  
format:
  html:
    # for more info, see
    # https://quarto.org/docs/output-formats/html-themes.html
    theme: [sandstone, theme.scss]
    # sets the background of inline code and code output but not code blocks?
    # also overrides code-bg in the SCSS file
    # monobackgroundcolor: '#fafafa'

jupyter: julia-1.9
execute:
  cache: false    # inline results conflict with cache use
  freeze: auto
