project:
  type: book

book:
  title: "Embrace Uncertainty"
  subtitle: "Mixed-effects models with Julia"
  author: 
    - name: Phillip Alday
      affiliation: Beacon Biosignals
    - name: Reinhold Kliegl
      affilitation: University of Potsdam
    - name: Douglas Bates
      affilitation: University of Wisconsin - Madison
  date: "2022-04-12"
  chapters:
    - index.qmd
    - intro.qmd
    - multiple.qmd
    - longitudinal.qmd
    - linalg.qmd
    - largescale.qmd
    - glmmbinomial.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

jupyter: julia-1.7
