project:
  type: book
  output-dir: docs

book:
  title: "Embrace Uncertainty"
  subtitle: "Mixed-effects models with Julia"
  author: "Phillip Alday, Reinhold Kliegl, and Douglas Bates"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - multiple.qmd
    - longitudinal.qmd
    - largescaledesigned.qmd
    - largescaleobserved.qmd
    - glmmbernoulli.qmd
    - references.qmd
  appendices:
    - datatables.qmd
    - linalg.qmd
    - aGHQ.qmd
    - viz.qmd

execute-dir: project

bibliography: references.bib
csl: apa-annotated-bibliography.csl

format:
  html:
    # for more info, see
    # https://quarto.org/docs/output-formats/html-themes.html
    theme: [sandstone, theme.scss]
    # sets the background of inline code and code output but not code blocks?
    # also overrides code-bg in the SCSS file
    # monobackgroundcolor: '#fafafa'

jupyter: julia-1.9
execute:
  cache: true
  freeze: auto
