project:
  type: book
  output-dir: docs

book:
  title: "Embrace Uncertainty"
  subtitle: "Mixed-effects models with Julia"
  author: "Phillip Alday, Reinhold Kliegl, and Douglas Bates"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - multiple.qmd
    - longitudinal.qmd
    - largescale.qmd
    - glmmbinomial.qmd
    - references.qmd
  appendices: 
    - linalg.qmd
    - contrasts_kwdyz11.qmd
    - contrasts_fggk21.qmd

execute-dir: project

bibliography: references.bib
csl: apa-annotated-bibliography.csl

format:
  html:
    theme: cosmo

jupyter: julia-1.8
