[projects]

  [projects.default]
  contents = [
    "intro",
    "multiple",
    "longitudinal",
#    "theory",
    "GLMMBinomial",
    "linalg",
    "references",
  ]
  port = 8042

  # Extra directories to be copied.
  extra_directories = [
  ]

  online_url = "https://embraceuncertainty.io"

  output_filename = "embraceuncertainty"
