# Preface {.unnumbered}

The purpose of this book is to introduce *mixed-effects models* and their use in the analysis of data with multiple sources of random variation in the response.
Such data are common in research in the social sciences.

The practical aspects of fitting such models to experimental or observational data and in evaluating such models are introduced through the [Julia programming language](https://julialang.org) and its [MixedModels](https://github.com/JuliaStats/MixedModels.jl) package.

This book is intended for researchers in applications areas, such as Psychology or Linguistics, and for researchers in Statistical methods.
Some of the technical discussions, especially in the appendices, may be rather daunting for applications-area researchers, who should feel free to skim those sections.
The purpose of those technical discussions is to establish a firm mathematical and theoretical basis for the computational methods.

This book has been produced with Quarto.  To learn more about Quarto books visit [https://quarto.org/docs/books](https://quarto.org/docs/books).

*This page was rendered from git revision {{< git-rev short=true >}} using Quarto {{< version >} and Julia {{< julia >}}.*
