<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Embrace Uncertainty - 1&nbsp; A Simple, Linear, Mixed-Effects Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./multiple.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./intro.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">A Simple, Linear, Mixed-Effects Model</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Embrace Uncertainty</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">A Simple, Linear, Mixed-Effects Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Models With Multiple Random-effects Terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./longitudinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Models for Longitudinal Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./largescaledesigned.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">A large-scale designed experiment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./largescaleobserved.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">A large-scale observational study</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glmmbernoulli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Generalized Linear Mixed Models for Binary Responses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datatables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Working with data tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linalg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Linear Algebra for Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aGHQ.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">GLMM log-likelihood</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-memod" id="toc-sec-memod" class="nav-link active" data-scroll-target="#sec-memod"><span class="header-section-number">1.1</span> Mixed-effects models</a></li>
  <li><a href="#sec-DyestuffData" id="toc-sec-DyestuffData" class="nav-link" data-scroll-target="#sec-DyestuffData"><span class="header-section-number">1.2</span> The dyestuff and dyestuff2 data</a>
  <ul class="collapse">
  <li><a href="#sec-dyestuff" id="toc-sec-dyestuff" class="nav-link" data-scroll-target="#sec-dyestuff"><span class="header-section-number">1.2.1</span> The dyestuff data</a></li>
  <li><a href="#sec-dyestuff2" id="toc-sec-dyestuff2" class="nav-link" data-scroll-target="#sec-dyestuff2"><span class="header-section-number">1.2.2</span> The dyestuff2 data</a></li>
  </ul></li>
  <li><a href="#sec-fittinglmms" id="toc-sec-fittinglmms" class="nav-link" data-scroll-target="#sec-fittinglmms"><span class="header-section-number">1.3</span> Fitting linear mixed models</a>
  <ul class="collapse">
  <li><a href="#sec-dyestuffLMM" id="toc-sec-dyestuffLMM" class="nav-link" data-scroll-target="#sec-dyestuffLMM"><span class="header-section-number">1.3.1</span> A model for the dyestuff data</a></li>
  <li><a href="#sec-printeddetails" id="toc-sec-printeddetails" class="nav-link" data-scroll-target="#sec-printeddetails"><span class="header-section-number">1.3.2</span> Details of the printed display</a></li>
  <li><a href="#sec-dyestuff2lmm" id="toc-sec-dyestuff2lmm" class="nav-link" data-scroll-target="#sec-dyestuff2lmm"><span class="header-section-number">1.3.3</span> A model for the dyestuff2 data</a></li>
  </ul></li>
  <li><a href="#sec-modelformulation" id="toc-sec-modelformulation" class="nav-link" data-scroll-target="#sec-modelformulation"><span class="header-section-number">1.4</span> Model formulation</a></li>
  <li><a href="#sec-furtherassess" id="toc-sec-furtherassess" class="nav-link" data-scroll-target="#sec-furtherassess"><span class="header-section-number">1.5</span> Variability of parameter estimates</a>
  <ul class="collapse">
  <li><a href="#sec-confints" id="toc-sec-confints" class="nav-link" data-scroll-target="#sec-confints"><span class="header-section-number">1.5.1</span> Confidence intervals on the parameters</a></li>
  <li><a href="#sec-dsm01trace" id="toc-sec-dsm01trace" class="nav-link" data-scroll-target="#sec-dsm01trace"><span class="header-section-number">1.5.2</span> Tracking the progress of the iterations</a></li>
  </ul></li>
  <li><a href="#sec-assessRE" id="toc-sec-assessRE" class="nav-link" data-scroll-target="#sec-assessRE"><span class="header-section-number">1.6</span> Assessing the random effects</a></li>
  <li><a href="#sec-stylistic" id="toc-sec-stylistic" class="nav-link" data-scroll-target="#sec-stylistic"><span class="header-section-number">1.7</span> Some stylistic conventions</a></li>
  <li><a href="#sec-ChIntroSummary" id="toc-sec-ChIntroSummary" class="nav-link" data-scroll-target="#sec-ChIntroSummary"><span class="header-section-number">1.8</span> Chapter summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-examlmm" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">A Simple, Linear, Mixed-Effects Model</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this book we describe the theory behind a type of statistical model called <em>mixed-effects</em> models and the practice of fitting and analyzing such models using the <a href="https://github.com/JuliaStats/MixedModels.jl">MixedModels</a> package for <a href="https://julialang.org">Julia</a>. These models are used in many different disciplines. Because the descriptions of the models can vary markedly between disciplines, we begin by describing what mixed-effects models are and by exploring a very simple example of one type of mixed model, the <em>linear mixed model</em>.</p>
<p>This simple example allows us to illustrate the use of the <code>LinearMixedModel</code> type in the <code>MixedModels</code> package for fitting such models and for analyzing the fitted model. We also describe methods of assessing the precision of the parameter estimates and of visualizing the conditional distribution of the random effects, given the observed data.</p>
<section id="sec-memod" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec-memod"><span class="header-section-number">1.1</span> Mixed-effects models</h2>
<p>Mixed-effects models, like many other types of statistical models, describe a relationship between a <em>response</em> variable and some of the <em>covariates</em> that have been measured or observed along with the response. In mixed-effects models at least one of the covariates is a <em>categorical</em> covariate representing experimental or observational “units” in the data set. In the example from the chemical industry that is given in this chapter, the observational unit is the batch of an intermediate product used in production of a dye. In medical and social sciences the observational units are often the human or animal subjects in the study. In agriculture the experimental units may be the plots of land or the specific plants being studied.</p>
<p>In all of these cases the categorical covariate or covariates are observed at a set of discrete <em>levels</em>. We may use numbers, such as subject identifiers, to designate the particular levels that we observed but these numbers are simply labels. The important characteristic of a categorical covariate is that, at each observed value of the response, the covariate takes on the value of one of a set of distinct levels.</p>
<p>Parameters associated with the particular levels of a covariate are sometimes called the “effects” of the levels. If the set of possible levels of the covariate is fixed and reproducible we model the covariate using <em>fixed-effects</em> parameters. If the levels that we observed represent a random sample from the set of all possible levels we incorporate <em>random effects</em> in the model.</p>
<p>There are two things to notice about this distinction between fixed-effects parameters and random effects. First, the names are misleading because the distinction between fixed and random is more a property of the levels of the categorical covariate than a property of the effects associated with them. Second, we distinguish between “fixed-effects parameters”, which are indeed parameters in the statistical model, and “random effects”, which, strictly speaking, are not parameters. As we will see shortly, random effects are unobserved random variables.</p>
<p>To make the distinction more concrete, suppose that we wish to model the annual reading test scores for students in a school district and that the covariates recorded with the score include a student identifier and the student’s gender. Both of these are categorical covariates. The levels of the gender covariate, male and female, are fixed. If we consider data from another school district or we incorporate scores from earlier tests, we will not change those levels. On the other hand, the students whose scores we observed would generally be regarded as a sample from the set of all possible students whom we could have observed. Adding more data, either from more school districts or from results on previous or subsequent tests, will increase the number of distinct levels of the student identifier.</p>
<p><em>Mixed-effects models</em> or, more simply, <em>mixed models</em> are statistical models that incorporate both fixed-effects parameters and random effects. Because of the way that we will define random effects, a model with random effects always includes at least one fixed-effects parameter. Thus, any model with random effects is a mixed model.</p>
<p>We characterize the statistical model in terms of two random variables: a <span class="math inline">\(q\)</span>-dimensional vector of random effects represented by the random variable <span class="math inline">\({\mathcal{B}}\)</span> and an <span class="math inline">\(n\)</span>-dimensional response vector represented by the random variable <span class="math inline">\({\mathcal{Y}}\)</span>. (We use upper-case “script” characters to denote random variables. The corresponding lower-case upright letter denotes a particular value of the random variable, with vector-valued random variable values in boldface.) We observe the value, <span class="math inline">\({\mathbf{y}}\)</span>, of <span class="math inline">\({\mathcal{Y}}\)</span>. We do not observe the value, <span class="math inline">\({\mathbf{b}}\)</span>, of <span class="math inline">\({\mathcal{B}}\)</span>.</p>
<p>When formulating the model we describe the unconditional distribution of <span class="math inline">\({\mathcal{B}}\)</span> and the conditional distribution, <span class="math inline">\(({\mathcal{Y}}|{\mathcal{B}}={\mathbf{b}})\)</span>. The descriptions of the distributions involve the form of the distribution and the values of certain parameters. We use the observed values of the response and the covariates to estimate these parameters and to make inferences about them.</p>
<p>That’s the big picture. Now let’s make this more concrete by describing a particular, versatile class of mixed models called linear mixed models and by studying a simple example of such a model. First we describe the data in the example.</p>
</section>
<section id="sec-DyestuffData" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sec-DyestuffData"><span class="header-section-number">1.2</span> The dyestuff and dyestuff2 data</h2>
<p>Models with random effects have been in use for a long time. The first edition of the classic book, <em>Statistical Methods in Research and Production</em>, edited by O.L. Davies, was published in 1947 and contained examples of the use of random effects to characterize batch-to-batch variability in chemical processes. The data from one of these examples are available as the <code>dyestuff</code> data in the <code>MixedModels</code> package. In this section we describe and plot these data and introduce a second example, the <code>dyestuff2</code> data, described in <span class="citation" data-cites="box73:_bayes_infer_statis_analy">Box &amp; Tiao (<a href="references.html#ref-box73:_bayes_infer_statis_analy" role="doc-biblioref">1973</a>)</span>.</p>
<section id="sec-dyestuff" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="sec-dyestuff"><span class="header-section-number">1.2.1</span> The dyestuff data</h3>
<p>The data are described in <span class="citation" data-cites="davies72:_statis_method_in_resear_and_produc">Davies &amp; Goldsmith (<a href="references.html#ref-davies72:_statis_method_in_resear_and_produc" role="doc-biblioref">1972</a>, Table&nbsp;6.3, p.&nbsp;131)</span>, the fourth edition of the book mentioned above, as coming from</p>
<blockquote class="blockquote">
<p>an investigation to find out how much the variation from batch to batch in the quality of an intermediate product (H-acid) contributes to the variation in the yield of the dyestuff (Naphthalene Black 12B) made from it. In the experiment six samples of the intermediate, representing different batches of works manufacture, were obtained, and five preparations of the dyestuff were made in the laboratory from each sample. The equivalent yield of each preparation as grams of standard colour was determined by dye-trial.</p>
</blockquote>
<p>To access these data within <code>Julia</code> we must first attach this package, and others that we will use, to our session.</p>
<div class="cell" data-execution_count="1">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">AlgebraOfGraphics </span><span class="co"># high-level graphics</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">CairoMakie        </span><span class="co"># graphics back-end</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">CategoricalArrays </span><span class="co"># factors and ordered factors</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DataFrameMacros   </span><span class="co"># elegant DataFrame manipulation</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DataFrames        </span><span class="co"># DataFrame implementation</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="fu">contains</span>(<span class="fu">first</span>(<span class="bu">Sys</span>.<span class="fu">cpu_info</span>()).model, <span class="st">"Intel"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="im">using</span> <span class="bu">MKL             </span><span class="co"># faster LAPACK on Intel processors</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Markdown          </span><span class="co"># utilities for generating markdown text</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">MixedModels       </span><span class="co"># fit and examine mixed-effects models</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">MixedModelsMakie  </span><span class="co"># graphics for mixed-effects models</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Printf            </span><span class="co"># formatted printing</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">ProgressMeter     </span><span class="co"># progress of optimizer iterations</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Random            </span><span class="co"># random number generation</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">StatsBase         </span><span class="co"># basic statistical summaries</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">AlgebraOfGraphics</span>: AlgebraOfGraphics as AoG <span class="co"># for easy access to some non exported methods</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>CairoMakie.<span class="fu">activate!</span>(; <span class="kw">type</span><span class="op">=</span><span class="st">"svg"</span>);</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>ProgressMeter.<span class="fu">ijulia_behavior</span>(<span class="op">:</span>clear);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>[ Info: Precompiling CategoricalArrays [324d7699-5711-5eae-9e2f-1d82baa6b597]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[ Info: Precompiling CategoricalArraysJSONExt [3659b7b4-73bc-5a91-ba4f-cc4948098fdb]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[ Info: Precompiling DataFrameMacros [75880514-38bc-4a95-a458-c2aea5a3a702]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[ Info: Precompiling CategoricalArraysSentinelArraysExt [25d60f2f-6134-5c9e-b13a-96ac465bddcb]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[ Info: Precompiling CategoricalArraysRecipesBaseExt [b7a5aa15-52bc-53b2-90b5-730883a6b80e]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[ Info: Precompiling CategoricalArraysStructTypesExt [e0b1e8f7-f9d4-55ed-aa4c-3cb4a66b5cfe]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[ Info: Precompiling MixedModelsMakie [b12ae82c-6730-437f-aff9-d2c38332a376]</code></pre>
</div>
</div>
<p>A package must be attached before any of the data sets or functions in the package can be used. If entering this line results in an error report stating that there is no package by one of these names then you must first install the package(s). If you are using Julia version 1.8.0 or later the error report will include instructions on how to do this.</p>
<p>In what follows, we will assume that these packages have been installed and attached to the session before any of the code shown has been run.</p>
<p>The <code>MixedModels</code> package includes several datasets that are used in examples and in tests of the package. Individual datasets can be loaded with the <code>dataset</code> function. To allow for other packages to incorporate their own <code>dataset</code> function without causing name clashes, this function is not exported and must be called with the fully-qualified name <code>MixedModels.dataset</code>. (If this explanation sounds like gibberish to you, the bottom line is that you must use <code>MixedModels.dataset(:dyestuff)</code> and not just <code>dataset(:dyestuff)</code>.)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Add metadata to Arrow files for datasets</p>
</div>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dyestuff <span class="op">=</span> MixedModels.<span class="fu">dataset</span>(<span class="op">:</span>dyestuff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>Arrow.Table with 30 rows, 2 columns, and schema:
 :batch  String
 :yield  Int16</code></pre>
</div>
</div>
<p>The output indicates that this dataset is a <code>Table</code> read from a file in the <a href="https://arrow.apache.org">Arrow</a> data format.</p>
<p>A <code>Table</code> is a general, but “bare bones”, tabular form defined in the <a href="https://github.com/JuliaData/Tables.jl">Tables</a> package. This particular table, read from an <code>Arrow</code> file, will be read-only. Often it is convenient to convert the read-only table form to a <code>DataFrame</code> to be able to use the full power of the <a href="https://github.com/JuliaData/DataFrames.jl">DataFrames</a> package.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dyestuff <span class="op">=</span> <span class="fu">DataFrame</span>(dyestuff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div><div style="float: left;"><span>30×2 DataFrame</span></div><div style="float: right;"><span style="font-style: italic;">5 rows omitted</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">batch</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">yield</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int16">Int16</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1545</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1440</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1440</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1520</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1580</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1540</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1555</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">8</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1490</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1560</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">10</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1495</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">11</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">1595</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">12</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">1550</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">13</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">1605</td>
</tr>
<tr class="even">
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">19</td>
<td style="text-align: left;">D</td>
<td style="text-align: right;">1465</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">20</td>
<td style="text-align: left;">D</td>
<td style="text-align: right;">1545</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">21</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1595</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">22</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1630</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">23</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1515</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">24</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1635</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">25</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1625</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">26</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1520</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">27</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1455</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">28</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1450</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">29</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1480</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">30</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1445</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The <code>describe</code> method for a <code>DataFrame</code> provides a concise description of the structure of the data,</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(dyestuff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><div style="float: left;"><span>2×7 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">nmissing</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">eltype</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Symbol">Symbol</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Nothing, Float64}">Union…</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Any">Any</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Nothing, Float64}">Union…</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Any">Any</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="DataType">DataType</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">batch</td>
<td style="text-align: left; font-style: italic;"></td>
<td style="text-align: left;">A</td>
<td style="text-align: left; font-style: italic;"></td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">String</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">yield</td>
<td style="text-align: left;">1527.5</td>
<td style="text-align: left;">1440</td>
<td style="text-align: left;">1530.0</td>
<td style="text-align: left;">1635</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Int16</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Combining this information with the initial description of the <code>Table</code> we see that the data frame consists of 30 observations of the <code>yield</code>, the response variable, and of the covariate, <code>batch</code>, which is a categorical variable whose levels are character strings.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(dyestuff.batch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>Arrow.DictEncoded{String, Int8, Arrow.List{String, Int32, Vector{UInt8}}}</code></pre>
</div>
</div>
<p>(<code>DictEncoded</code> is the <code>Arrow</code> term for a categorical structure where the levels form a dictionary or lookup table and the values are stored as indices into this lookup table.)</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(<span class="fu">levels</span>(dyestuff.batch))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>["A", "B", "C", "D", "E", "F"]</code></pre>
</div>
</div>
<p>If the labels for the factor levels are arbitrary, as they are here, we will use letters instead of numbers for the labels. That is, we label the batches as <code>"A"</code> through <code>"F"</code> rather than <code>1</code> through <code>6</code>. When the labels are letters it is clear that the variable is categorical. When the labels are numbers a categorical covariate can be mistaken for a numeric covariate, with unintended consequences.</p>
<p>It is a good practice to apply <code>describe</code> to any data frame the first time you work with it and to check carefully that any categorical variables are indeed represented as factors.</p>
<p>The data in a data frame are viewed as a table with columns corresponding to variables and rows to observations. The functions <code>first</code> and <code>last</code> select the first or last few rows of the table.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">first</span>(dyestuff, <span class="fl">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div><div style="float: left;"><span>7×2 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">batch</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">yield</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int16">Int16</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1545</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1440</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1440</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1520</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1580</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1540</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1555</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">last</span>(dyestuff, <span class="fl">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div><div style="float: left;"><span>7×2 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">batch</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">yield</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int16">Int16</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1635</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1625</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1520</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1455</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1450</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1480</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1445</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>or we could tabulate the data using <code>groupby</code> and <code>combine</code> from <a href="https://github.com/JuliaData/DataFrames.jl">DataFrames</a>.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">combine</span>(<span class="fu">groupby</span>(dyestuff, <span class="op">:</span>batch), <span class="op">:</span>yield <span class="op">=&gt;</span> mean, nrow <span class="op">=&gt;</span> <span class="op">:</span>n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><div style="float: left;"><span>6×3 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">batch</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">yield_mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">n</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">1505.0</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">1528.0</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">1564.0</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">D</td>
<td style="text-align: right;">1498.0</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">1600.0</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1470.0</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Although this table does show us an important property of the data, namely that there are exactly 5 observations on each batch — a property that we will describe by saying that the data are <em>balanced</em> with respect to <code>batch</code> — we usually learn much more about the structure of such data from plots like <a href="#fig-dyestuffdata">Figure&nbsp;<span>1.1</span></a></p>
<div class="cell" data-execution_count="10">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="st">    _meanrespfrm(df, :resp::Symbol, :grps::Symbol; sumryf::Function=mean)</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="st">Returns a `DataFrame` created from df with the levels of `grps` reordered according to</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="st">`combine(groupby(df, grps), resp =&gt; sumryf)` and this summary DataFrame, also with the</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="st">levels of `grps` reordered.</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">_meanrespfrm</span>(</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  df,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  resp<span class="op">::</span><span class="dt">Symbol</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  grps<span class="op">::</span><span class="dt">Symbol</span>;</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  sumryf<span class="op">::</span><span class="dt">Function</span>=mean,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ensure the relevant columns are types that Makie can deal with</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  df <span class="op">=</span> <span class="fu">transform</span>(</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    df,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    resp <span class="op">=&gt;</span> <span class="dt">Array</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    grps <span class="op">=&gt;</span> CategoricalArray;</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    renamecols<span class="op">=</span><span class="cn">false</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># create a summary table by mean resp</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  sumry <span class="op">=</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sort!</span>(<span class="fu">combine</span>(<span class="fu">groupby</span>(df, grps), resp <span class="op">=&gt;</span> sumryf <span class="op">=&gt;</span> resp), resp)</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  glevs <span class="op">=</span> <span class="fu">string</span>.(sumry[!, grps])   <span class="co"># group levels in ascending order of mean resp</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levels!</span>(df[!, grps], glevs)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levels!</span>(sumry[!, grps], glevs)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> df, sumry</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>  df, sumry <span class="op">=</span> <span class="fu">_meanrespfrm</span>(dyestuff, <span class="op">:</span>yield, <span class="op">:</span>batch)</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>  mp <span class="op">=</span> <span class="fu">mapping</span>(</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>yield <span class="op">=&gt;</span> <span class="st">"Yield of dyestuff [g]"</span>,</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>batch <span class="op">=&gt;</span> <span class="st">"Batch of intermediate product"</span>,</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">draw</span>(</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">data</span>(df) <span class="op">*</span> mp <span class="op">*</span> <span class="fu">visual</span>(Scatter; marker<span class="op">=</span><span class="ch">'○'</span>, markersize<span class="op">=</span><span class="fl">12</span>)) <span class="op">+</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">data</span>(sumry) <span class="op">*</span> mp <span class="op">*</span> <span class="fu">visual</span>(Lines));</span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>    figure<span class="op">=</span>(; resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">400</span>)),</span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<div id="fig-dyestuffdata" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-dyestuffdata-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.1: Yield of dyestuff by batch. The line joins the mean yields.</figcaption>
</figure>
</div>
</div>
</div>
<p>than we do from numerical summaries.</p>
<p>In <a href="#fig-dyestuffdata">Figure&nbsp;<span>1.1</span></a> we can see that there is considerable variability in yield, even for preparations from the same batch, but there is also noticeable batch-to-batch variability. For example, four of the five preparations from batch F produced lower yields than did any of the preparations from batches B, C, and E.</p>
<p>This plot, and essentially all the other plots in this book, were created using the <a href="https://makie.juliaplots.io">Makie</a> package (<span class="citation" data-cites="DanischKrumbiegel2021">Danisch &amp; Krumbiegel (<a href="references.html#ref-DanischKrumbiegel2021" role="doc-biblioref">2021</a>)</span>).</p>
<p>In <code>yet-to-be-written-appendix</code> we review some of the principles of data graphics, such as reordering the levels of the factor by increasing mean response, that enhance the informativeness of the plot. For example, in this plot the levels of <code>batch</code> are sorted by increasing mean yield, to make visual comparisons between batches easier, and the vertical positions are <em>jittered</em> to avoid overplotting of points. (Note that the two lowest yields of samples from batch <code>A</code> are identical.)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Jittering has not yet been added.</p>
</div>
</div>
<p>At this point we will concentrate on the information conveyed by the plot and not on how the plot is created.</p>
<p>In <a href="#sec-fittinglmms"><span>Section&nbsp;1.3</span></a> we will use mixed models to quantify the variability in yield between batches. For the time being let us just note that the particular batches used in this experiment are a selection or sample from the set of all batches that we wish to consider. Furthermore, the extent to which one particular batch tends to increase or decrease the mean yield of the process — in other words, the “effect” of that particular batch on the yield — is not as interesting to us as is the extent of the variability between batches. For the purposes of designing, monitoring and controlling a process we want to predict the yield from future batches, taking into account the batch-to-batch variability and the within-batch variability. Being able to estimate the extent to which a particular batch in the past increased or decreased the yield is not usually an important goal for us. We will model the effects of the batches as random effects rather than as fixed-effects parameters.</p>
</section>
<section id="sec-dyestuff2" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="sec-dyestuff2"><span class="header-section-number">1.2.2</span> The dyestuff2 data</h3>
<p>The data are simulated data presented in <span class="citation" data-cites="box73:_bayes_infer_statis_analy">Box &amp; Tiao (<a href="references.html#ref-box73:_bayes_infer_statis_analy" role="doc-biblioref">1973</a>, Table 5.1.4, p.&nbsp;247)</span> where the authors state</p>
<blockquote class="blockquote">
<p>These data had to be constructed for although examples of this sort undoubtedly occur in practice they seem to be rarely published.</p>
</blockquote>
<p>The structure and summary</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dyestuff2 <span class="op">=</span> MixedModels.<span class="fu">dataset</span>(<span class="op">:</span>dyestuff2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>Arrow.Table with 30 rows, 2 columns, and schema:
 :batch  String
 :yield  Float64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dyestuff2 <span class="op">=</span> <span class="fu">DataFrame</span>(dyestuff2)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(dyestuff2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div><div style="float: left;"><span>2×7 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">nmissing</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">eltype</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Symbol">Symbol</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Nothing, Float64}">Union…</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Any">Any</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Nothing, Float64}">Union…</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Any">Any</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="DataType">DataType</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">batch</td>
<td style="text-align: left; font-style: italic;"></td>
<td style="text-align: left;">A</td>
<td style="text-align: left; font-style: italic;"></td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">String</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">yield</td>
<td style="text-align: left;">5.6656</td>
<td style="text-align: left;">-0.892</td>
<td style="text-align: left;">5.365</td>
<td style="text-align: left;">13.434</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Float64</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>are intentionally similar to those of the <code>dyestuff</code> data.</p>
<p>A data plot (<a href="#fig-dyestuff2data">Figure&nbsp;<span>1.2</span></a>)</p>
<div class="cell" data-execution_count="13">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  df, sumry <span class="op">=</span> <span class="fu">_meanrespfrm</span>(dyestuff2, <span class="op">:</span>yield, <span class="op">:</span>batch)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  mp <span class="op">=</span> <span class="fu">mapping</span>(<span class="op">:</span>yield <span class="op">=&gt;</span> <span class="st">"Simulated yield"</span>, <span class="op">:</span>batch <span class="op">=&gt;</span> <span class="st">"Batch"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">draw</span>(</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">data</span>(df) <span class="op">*</span> mp <span class="op">*</span> <span class="fu">visual</span>(Scatter; marker<span class="op">=</span><span class="ch">'○'</span>, markersize<span class="op">=</span><span class="fl">12</span>)) <span class="op">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">data</span>(sumry) <span class="op">*</span> mp <span class="op">*</span> <span class="fu">visual</span>(Lines));</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    figure<span class="op">=</span>(; resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">400</span>)),</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<div id="fig-dyestuff2data" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-dyestuff2data-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.2: Artificial data of yield by batch. The line joins the mean yields.</figcaption>
</figure>
</div>
</div>
</div>
<p>shows that the batch-to-batch variability in these data is small compared to the within-batch variability.</p>
<p>In some approaches to mixed models it can be difficult to fit models to such data. Paradoxically, small “variance components” can be more difficult to estimate than large variance components.</p>
<p>The methods we will present are not compromised when estimating small variance components.</p>
</section>
</section>
<section id="sec-fittinglmms" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sec-fittinglmms"><span class="header-section-number">1.3</span> Fitting linear mixed models</h2>
<p>Before we formally define a linear mixed model, let’s go ahead and fit models to these data sets using <code>MixedModels</code>. The simplest way to do this is to use the generic <code>fit</code> function with arguments describing the type of model to be fit (i.e.&nbsp;<code>MixedModel</code>), a <em>formula</em> specifying the model and the <em>data</em> on which to evaluate the formula.</p>
<p>We will explain the structure of the formula after we have considered an example.</p>
<section id="sec-dyestuffLMM" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="sec-dyestuffLMM"><span class="header-section-number">1.3.1</span> A model for the dyestuff data</h3>
<p>We fit a model to the data allowing for an overall level of the <code>yield</code> and for an additive random effect for each level of <code>batch</code>.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dsm01 <span class="op">=</span> <span class="kw">let</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  form <span class="op">=</span> <span class="pp">@formula</span>(yield <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> (<span class="fl">1</span> <span class="op">|</span> batch))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(MixedModel, form, dyestuff)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Est.</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">z</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">σ_batch</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1527.5000</td>
<td style="text-align: right;">17.6946</td>
<td style="text-align: right;">86.33</td>
<td style="text-align: right;">&lt;1e-99</td>
<td style="text-align: right;">37.2603</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residual</td>
<td style="text-align: right;">49.5101</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>By default, this compact display of mixed-effects model fits is used in <a href="https://jupyter.org">Jupyter</a> notebooks, which are the evaluation engine for <a href="https://quarto.org/docs/books/">quarto books</a> with Julia code chunks. To obtain more information we can <code>print</code> the model, as in</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(dsm01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood
 yield ~ 1 + (1 | batch)
   logLik   -2 logLik     AIC       AICc        BIC    
  -163.6635   327.3271   333.3271   334.2501   337.5307

Variance components:
            Column    Variance Std.Dev.
batch    (Intercept)  1388.3332 37.2603
Residual              2451.2501 49.5101
 Number of obs: 30; levels of grouping factors: 6

  Fixed-effects parameters:
────────────────────────────────────────────────
              Coef.  Std. Error      z  Pr(&gt;|z|)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
────────────────────────────────────────────────
(Intercept)  1527.5     17.6946  86.33    &lt;1e-99
────────────────────────────────────────────────</code></pre>
</div>
</div>
<p>The call to <code>fit</code> constructs a <code>LinearMixedModel</code> object, evaluates the <a href="https://en.wikipedia.org/wiki/Maximum_likelihood_estimation">maximum likelihood</a> parameter estimates, assigns the results to the name <code>dsm01</code>, and displays a summary of the fitted model.</p>
</section>
<section id="sec-printeddetails" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="sec-printeddetails"><span class="header-section-number">1.3.2</span> Details of the printed display</h3>
<p>The display of the fitted model has four major sections:</p>
<ol type="1">
<li>a description of the model that was fit</li>
<li>some statistics characterizing the model fit</li>
<li>a summary of properties of the random effects and</li>
<li>a summary of the fixed-effects parameter estimates.</li>
</ol>
<p>We consider each of these sections in turn.</p>
<p>The description section states that this is a linear mixed model in which the parameters have been estimate by maximum likelihood (ML). The model formula is displayed for later reference.</p>
<p>The display of a model fit by maximum likelihood provides several model-fit statistics such as Akaike’s Information Criterion <span class="citation" data-cites="saka:ishi:kita:1986">(<a href="references.html#ref-saka:ishi:kita:1986" role="doc-biblioref">Sakamoto et al., 1986</a>)</span>, Schwarz’s Bayesian Information Criterion <span class="citation" data-cites="schw:1978">(<a href="references.html#ref-schw:1978" role="doc-biblioref">Schwarz, 1978</a>)</span>, the log-likelihood at the parameter estimates, and negative twice the log-likelihood, which is the estimation criterion transformed to the scale of the <em>deviance</em>. For linear mixed models we refer to <code>-2 loglik</code> as the value of the <em>objective</em> because this is the value that is minimized during the optimization phase of fitting the model. To evaluate the <em>deviance</em> we should subtract the value of this criterion at a <em>saturated</em> or baseline model but it is not clear how to define such a baseline model in these cases.</p>
<p>However, it is still possible to perform <a href="https://en.wikipedia.org/wiki/Likelihood-ratio_test">likelihood ratio tests</a> of different models fit to the same data using the difference in the minimized objectives, because this difference is the same as the difference in the deviances. (Recall that a ratio of likelihoods corresponds to a difference in log-likelihoods.)</p>
<p>The third section is the table of estimates of parameters associated with the random effects. There are two sources of variability in the model we have fit, a batch-to-batch variability in the level of the response and the residual or per-observation variability — also called the within-batch variability. The name “residual” is used in statistical modeling to denote the part of the variability that cannot be explained or modeled with the other terms. It is the variation in the observed data that is “left over” after we have determined the estimates of the parameters in the other parts of the model.</p>
<p>Some of the variability in the response is associated with the fixed-effects terms. In this model there is only one such term, labeled as the <code>(Intercept)</code>. The name “intercept”, which is better suited to models based on straight lines written in a slope/intercept form, should be understood to represent an overall “typical” or mean level of the response in this case. (In case you are wondering about the parentheses around the name <code>(Intercept)</code>, they are included so that you can’t accidentally create a variable with a name that conflicts with this name.) The line labeled <code>batch</code> in the random effects table shows that the random effects added to the term, one for each level of the factor <code>batch</code>, are modeled as random variables whose unconditional variance is estimated as 1388.33 g<span class="math inline">\(^2\)</span> in the ML fit. The corresponding standard deviation is 37.26 g.</p>
<p>Note that the last column in the random effects summary table is the estimate of the variability expressed as a standard deviation rather than as a variance. These values are provided because usually it is easier to visualize standard deviations, which are on the scale of the response, than it is to visualize the magnitude of a variance. The values in this column are a simple re-expression (the square root) of the estimated variances. Do not confuse them with standard errors of the variance estimators, which are not given here. In <code>add-section-reference-here</code> we explain why we do not provide standard errors of variance estimates.</p>
<p>The line labeled <code>Residual</code> in this table gives the estimate of the variance of the residuals (also in g<span class="math inline">\(^2\)</span>) and its corresponding standard deviation. The estimated standard deviation of the residuals is 49.5 g.</p>
<p>The last line in the random effects table states the number of observations to which the model was fit and the number of levels of any “grouping factors” for the random effects. In this case we have a single random effects term, <code>(1|batch)</code>, in the model formula and the grouping factor for that term is <code>batch</code>. There will be a total of six random effects, one for each level of <code>batch</code>.</p>
<p>The final part of the printed display gives the estimates and standard errors of any fixed-effects parameters in the model. The only fixed-effects term in the model formula is the <code>1</code>, denoting a constant which, as explained above, is labeled as <code>(Intercept)</code>. The estimate of this parameter is 1527.5 g, which happens to be the mean yield across all the data - a consequence of the experiment being <em>balanced</em>, in the sense that there was the same number of observations for each batch.</p>
<p>This <em>coefficient table</em> also includes the <em>standard error</em> of the estimate, which is the estimated standard deviation of the estimator, a <code>z</code> ratio, which is the ratio of the estimate to its standard error, and the probability the absolute value of a standard normal distribution exceeding the absolute value of the <code>z</code> ratio.</p>
<p>If the hypothesis that the coefficient is zero is of interest, which is not the case here, then the value in the fourth column is an approximate p-value for the hypothesis test. An alternative measure of precision of the estimate - a coverage interval based on a <em>parametric bootstrap</em> - is presented in <a href="#sec-furtherassess"><span>Section&nbsp;1.5</span></a></p>
</section>
<section id="sec-dyestuff2lmm" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="sec-dyestuff2lmm"><span class="header-section-number">1.3.3</span> A model for the dyestuff2 data</h3>
<p>Fitting a similar model to the <code>dyestuff2</code> data produces an estimate <span class="math inline">\(\widehat{\sigma}_1=0\)</span>.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dsm02 <span class="op">=</span> <span class="kw">let</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  form <span class="op">=</span> <span class="pp">@formula</span>(yield <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> (<span class="fl">1</span> <span class="op">|</span> batch))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(MixedModel, form, dyestuff2)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(dsm02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood
 yield ~ 1 + (1 | batch)
   logLik   -2 logLik     AIC       AICc        BIC    
   -81.4365   162.8730   168.8730   169.7961   173.0766

Variance components:
            Column   Variance Std.Dev.
batch    (Intercept)   0.00000 0.00000
Residual              13.34610 3.65323
 Number of obs: 30; levels of grouping factors: 6

  Fixed-effects parameters:
───────────────────────────────────────────────
              Coef.  Std. Error     z  Pr(&gt;|z|)
───────────────────────────────────────────────
(Intercept)  5.6656    0.666986  8.49    &lt;1e-16
───────────────────────────────────────────────</code></pre>
</div>
</div>
<p>An estimate of <span class="math inline">\(0\)</span> for <span class="math inline">\(\sigma_1\)</span> does not mean that there is no variation between the groups. Indeed <a href="#fig-dyestuff2data">Figure&nbsp;<span>1.2</span></a> shows that there is some small amount of variability between the groups. The estimate, <span class="math inline">\(\widehat{\sigma}_1=0\)</span>, simply indicates that the level of “between-group” variability is not sufficient to warrant incorporating random effects in the model.</p>
<p>This point is worth reiterating. An estimate of zero for a variance component does not imply that there is no variability between the groups. There will always be variability between groups that is induced by the per-observation variability. If we arbitrarily divided 30 observations from a homogeneous distribution into six groups of five observations, which is likely the way that this sample was simulated, the sample averages would inherit a level of variability from the original sample. What is being estimated in the variance component for <code>batch</code> is the <em>excess</em> variability between groups beyond that induced by the residual variability.</p>
<p>In other words, an estimate <span class="math inline">\(\widehat{\sigma}_1=0\)</span> is not inconsistent with the model. The important point to take away from this example is that we must allow for the estimates of variance components to be zero.</p>
<p>We describe such a model as being <em>degenerate</em>, in the sense that the estimated distribution of the random effects is a <a href="https://en.wikipedia.org/wiki/Degenerate_distribution">degenerate distribution</a>, representing a point mass at zero. It corresponds to a linear model in which we have removed the random effects associated with <code>batch</code>.</p>
<p>Degenerate models can and do occur in practice. Even when the final fitted model is not degenerate, we must allow for such models when determining the parameter estimates through numerical optimization.</p>
<p>To reiterate, this model can be reduced to a linear model because the random effects are inert, in the sense that they have a variance of zero.</p>
</section>
</section>
<section id="sec-modelformulation" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="sec-modelformulation"><span class="header-section-number">1.4</span> Model formulation</h2>
<p>A common way of writing the statistical model being fit in <code>dsm01</code> and <code>dsm02</code> is as an expression for the i’th observation in the j’th batch <span class="math display">\[
y_{i,j}=\mu+b_j+\epsilon_{i,j},\quad i = 1,\dots,5;\;j=1,\dots,6
\]</span> with the further specification that the per-observation noise terms, <span class="math inline">\(\epsilon_{i,j}\)</span>, are independently and identically distributed as <span class="math inline">\({\mathcal{N}}(0, \sigma^2)\)</span> and the random effects, <span class="math inline">\(b_j\)</span>, are independently and identically distributed as <span class="math inline">\({\mathcal{N}}(0, \sigma_1^2)\)</span>. The three parameters in the model are the overall mean, <span class="math inline">\(\mu\)</span>, the standard deviation of the random effects, <span class="math inline">\(\sigma_1\)</span>, and the standard deviation of the per-observation noise, <span class="math inline">\(\sigma\)</span>.</p>
<p>Generalizing this formulation to unbalanced data sets and more complex models can become unwieldy. For the range of models shown in this book it is more convenient to use a matrix-vector representation in which the random effects are described as a <span class="math inline">\(q\)</span>-dimensional multivariate Gaussian random variable <span id="eq-mvbdist"><span class="math display">\[
{\mathcal{B}}\sim{\mathcal{N}}(\mathbf{0},\sigma_1^2{\mathbf{I}}) .
\tag{1.1}\]</span></span> The multivariate Gaussian distribution is described in more detail in <a href="linalg.html#sec-mvgaussian"><span>Section&nbsp;B.2.3</span></a>. At this point the important thing to know is that <a href="#eq-mvbdist">Equation&nbsp;<span>1.1</span></a> describes a vector of independent Gaussian random variables, each of which has mean <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma_1^2\)</span>.</p>
<p>The random effects are associated with the observations through a <em>model matrix</em>, <span class="math inline">\({\mathbf{Z}}\)</span>. For a model with <span class="math inline">\(n\)</span> observations and a total of <span class="math inline">\(q\)</span> random effects, <span class="math inline">\({\mathbf{Z}}\)</span> will be of size <span class="math inline">\(n\times q\)</span>. Furthermore, it is sparse - meaning that most of the elements of the matrix are zeros. In this case, <span class="math inline">\({\mathbf{Z}}\)</span> is the indicator matrix for the <code>batch</code> covariate.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>Zdsm01 <span class="op">=</span> <span class="fu">Int</span>.(<span class="fu">Matrix</span>(<span class="fu">only</span>(dsm01.reterms)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>30×6 Matrix{Int64}:
 1  0  0  0  0  0
 1  0  0  0  0  0
 1  0  0  0  0  0
 1  0  0  0  0  0
 1  0  0  0  0  0
 0  1  0  0  0  0
 0  1  0  0  0  0
 0  1  0  0  0  0
 0  1  0  0  0  0
 0  1  0  0  0  0
 0  0  1  0  0  0
 0  0  1  0  0  0
 0  0  1  0  0  0
 ⋮              ⋮
 0  0  0  1  0  0
 0  0  0  1  0  0
 0  0  0  0  1  0
 0  0  0  0  1  0
 0  0  0  0  1  0
 0  0  0  0  1  0
 0  0  0  0  1  0
 0  0  0  0  0  1
 0  0  0  0  0  1
 0  0  0  0  0  1
 0  0  0  0  0  1
 0  0  0  0  0  1</code></pre>
</div>
</div>
<p>The expression to produce that output first extracted the random-effects terms information from <code>dsm01</code>, extracted the term for the first grouping factor, checking that there is only one, converted it to a matrix and converted the matrix to integers to save on space when printing.</p>
<p>In cases like this we will often print out the transpose of the model matrix to save more space</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>Zdsm01<span class="op">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>6×30 adjoint(::Matrix{Int64}) with eltype Int64:
 1  1  1  1  1  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  1  1  1  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  1  1  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  1  1  1  1  1  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  1  1  1  1  1</code></pre>
</div>
</div>
<p>or, even more compact, as a sparse matrix pattern</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sparse</span>(Zdsm01<span class="op">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>6×30 SparseArrays.SparseMatrixCSC{Int64, Int64} with 30 stored entries:
⎡⠉⠉⠑⠒⠒⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⎤
⎣⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠤⠤⢄⣀⣀⎦</code></pre>
</div>
</div>
<p>The fixed-effects parameters, of which there is only one here, are gathered into a vector, <span class="math inline">\({\boldsymbol{\beta}}\)</span>, of length <span class="math inline">\(p\)</span>, and multiplied by another model matrix, <span class="math inline">\({\mathbf{X}}\)</span>, of size <span class="math inline">\(n\times p\)</span>.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>dsm01.β</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>1-element Vector{Float64}:
 1527.4999999999989</code></pre>
</div>
</div>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Int</span>.(dsm01.X<span class="op">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>1×30 Matrix{Int64}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1</code></pre>
</div>
</div>
<p>A linear model without random effects can be described as <span class="math inline">\({\mathcal{Y}}\sim{\mathcal{N}}({\mathbf{X}}{\boldsymbol{\beta}}, \sigma^2{\mathbf{I}})\)</span>. That is, the expected value of the response vector is the <em>linear predictor</em>, <span class="math inline">\({\mathbf{X}}{\boldsymbol{\beta}}\)</span>, and the covariance matrix of the multivariate Gaussian distribution for the response is <span class="math inline">\(\sigma^2{\mathbf{I}}\)</span>, corresponding to independent, constant variance per-observation noise terms.</p>
<p>For the linear mixed model, we describe the conditional distribution of the response, given a particular value, <span class="math inline">\({\mathbf{b}}\)</span>, of the random effects as multivariate Gaussian with mean determined by a linear predictor expression involving both the assumed random effects value, <span class="math inline">\({\mathbf{b}}\)</span>, and the fixed-effects parameter vector <span class="math inline">\({\boldsymbol{\beta}}\)</span>. <span class="math display">\[
({\mathcal{Y}}|{\mathcal{B}}={\mathbf{b}})\sim{\mathcal{N}}({\mathbf{X}}{\boldsymbol{\beta}}+{\mathbf{Z}}{\mathbf{b}},\sigma^2{\mathbf{I}})
\]</span></p>
<p>The complete model can be written as <span id="eq-lmmdist"><span class="math display">\[
\begin{aligned}
({\mathcal{Y}}|{\mathcal{B}}={\mathbf{b}})&amp;\sim{\mathcal{N}}({\mathbf{X}}{\boldsymbol{\beta}}+{\mathbf{Z}}{\mathbf{b}},\sigma^2{\mathbf{I}})\\
{\mathcal{B}}&amp;\sim{\mathcal{N}}(\mathbf{0},{\boldsymbol{\Sigma}}_\theta) .
\end{aligned}
\tag{1.2}\]</span></span></p>
<p>From these two distributions, the joint distribution of <span class="math inline">\({\mathcal{Y}}\)</span> and <span class="math inline">\({\mathcal{B}}\)</span>, which is also multivariate Gaussian, can be determined and from that the likelihood for the parameters, given the observed value <span class="math inline">\({\mathbf{y}}\)</span> of <span class="math inline">\({\mathcal{Y}}\)</span>.</p>
<p>Details on the derivation and evaluation of the log-likelihood are given in <a href="linalg.html#sec-lmmtheory"><span>Section&nbsp;B.7</span></a>. At this point the important results are that the <em>profiled</em> log-likelihood for models <code>dsm01</code> and <code>dsm02</code> can be evaluated directly (i.e.&nbsp;without an iterative optimization) from a single parameter, <span class="math inline">\(\theta=\sigma_1/\sigma\)</span>.</p>
<p>Furthermore, this profiled log-likelihood can be evaluated from a matrix of <span class="math inline">\({\mathbf{X}}'{\mathbf{X}}\)</span>-like products, <span class="math display">\[
{\mathbf{A}}=
\begin{bmatrix}
{\mathbf{Z}}'{\mathbf{Z}}&amp; {\mathbf{Z}}'{\mathbf{X}}&amp; {\mathbf{Z}}'{\mathbf{y}}\\
{\mathbf{X}}'{\mathbf{Z}}&amp; {\mathbf{X}}'{\mathbf{X}}&amp; {\mathbf{X}}'{\mathbf{y}}\\
{\mathbf{y}}'{\mathbf{Z}}&amp; {\mathbf{y}}'{\mathbf{X}}&amp; {\mathbf{y}}'{\mathbf{y}}
\end{bmatrix}
\]</span> which is stored in three pieces</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">first</span>(dsm01.A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>6×6 LinearAlgebra.Diagonal{Float64, Vector{Float64}}:
 5.0   ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   5.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   5.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   5.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   5.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   5.0</code></pre>
</div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>dsm01.A[<span class="fl">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>2×6 Matrix{Float64}:
    5.0     5.0     5.0     5.0     5.0     5.0
 7525.0  7640.0  7820.0  7490.0  8000.0  7350.0</code></pre>
</div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">last</span>(dsm01.A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>2×2 Matrix{Float64}:
    30.0  45825.0
 45825.0      7.01129e7</code></pre>
</div>
</div>
<p>The first, diagonal matrix is <span class="math inline">\({\mathbf{Z}}'{\mathbf{Z}}\)</span>. A simple, scalar random effects term like <code>(1|batch)</code> in the formula for models <code>dsm01</code> and <code>dsm02</code> results in <span class="math inline">\({\mathbf{Z}}\)</span> being the indicator matrix for the levels of the grouping factor and, hence, in a diagonal <span class="math inline">\({\mathbf{Z}}'{\mathbf{Z}}\)</span>, whose diagonal elements are the frequencies of the levels. Thus this block shows that there are exactly 5 observations on each of the 6 batches.</p>
<p>The second, rectangular matrix is <span class="math inline">\(\begin{bmatrix} {\mathbf{Z}}'{\mathbf{X}}\\ {\mathbf{Z}}'{\mathbf{y}}\end{bmatrix}\)</span>. Again, the fact that <span class="math inline">\({\mathbf{Z}}\)</span> is the indicator matrix for the levels of the grouping factor and that <span class="math inline">\({\mathbf{X}}\)</span> is a single column of 1’s results in the frequencies of the levels of the factor in the first row of this block. The second row of this block consists of the sums of the yields for each batch.</p>
<p>The third, square symmetric matrix is <span class="math display">\[
\begin{bmatrix}
{\mathbf{X}}'{\mathbf{X}}&amp; {\mathbf{X}}'{\mathbf{y}}\\
{\mathbf{y}}'{\mathbf{X}}&amp; {\mathbf{y}}'{\mathbf{y}}
\end{bmatrix}
\]</span></p>
<p>The parameters enter into the computation via a <em>relative covariance factor</em>, <span class="math inline">\({\boldsymbol{\Lambda}}_{\boldsymbol\theta}\)</span>, which is the <span class="math inline">\(6\times 6\)</span> matrix <span class="math inline">\(\theta\,{\mathbf{I}}\)</span> in this case.</p>
<p>The method hinges on being able to evaluate efficiently the <em>Cholesky factor</em> (see <a href="linalg.html#sec-cholesky"><span>Section&nbsp;B.2.2</span></a> for details) of <span class="math display">\[
\begin{bmatrix}
{\boldsymbol{\Lambda}}_\theta'\mathbf{Z'Z}{\boldsymbol{\Lambda}}_\theta+{\mathbf{I}}&amp;
{\boldsymbol{\Lambda}}_\theta'\mathbf{Z'X} &amp; {\boldsymbol{\Lambda}}_\theta'\mathbf{Z'y} \\
\mathbf{X'Z}{\boldsymbol{\Lambda}}_\theta &amp; \mathbf{X'X} &amp; \mathbf{X'y} \\
\mathbf{y'Z}{\boldsymbol{\Lambda}}_\theta &amp; \mathbf{y'X} &amp; \mathbf{y'y}
\end{bmatrix}
\]</span></p>
<p>The optimal value of <span class="math inline">\(\theta\)</span> for model <code>dsm01</code> is</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">only</span>(dsm01.θ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>0.7525806394967323</code></pre>
</div>
</div>
<p>producing a lower Cholesky factor of</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sparseL</span>(dsm01; full<span class="op">=</span><span class="cn">true</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>8×8 SparseArrays.SparseMatrixCSC{Float64, Int32} with 21 stored entries:
    1.95752      ⋅           ⋅       …      ⋅           ⋅          ⋅ 
     ⋅          1.95752      ⋅              ⋅           ⋅          ⋅ 
     ⋅           ⋅          1.95752         ⋅           ⋅          ⋅ 
     ⋅           ⋅           ⋅              ⋅           ⋅          ⋅ 
     ⋅           ⋅           ⋅              ⋅           ⋅          ⋅ 
     ⋅           ⋅           ⋅       …     1.95752      ⋅          ⋅ 
    1.92228     1.92228     1.92228        1.92228     2.79804     ⋅ 
 2893.03     2937.24     3006.45        2825.75     4274.01     271.178</code></pre>
</div>
</div>
</section>
<section id="sec-furtherassess" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="sec-furtherassess"><span class="header-section-number">1.5</span> Variability of parameter estimates</h2>
<p>The parameter estimates in a statistical model represent our “best guess” at the unknown values of the model parameters and, as such, are important results in statistical modeling. However, they are not the whole story. Statistical models characterize the variability in the data and we should assess the effect of this variability on the precision of the parameter estimates and of predictions made from the model.</p>
<p>One method of assessing the variability in the parameter estimates is through a <a href="https://en.wikipedia.org/wiki/Bootstrapping_(statistics)#Parametric_bootstrap">parametric bootstrap</a>, a process where a large number of data sets are simulated from the assumed model using the estimated parameter values as the “true” parameter values. The distribution of the parameter estimators is inferred from the distribution of the parameter estimates from these generated data sets.</p>
<p>This method is well-suited to Julia code because refitting an existing model to a simulated data set can be very fast.</p>
<p>For methods that involve simulation, it is best to initialize a random number generator to a known state so that the “random” sample can be reproduced if desired. Beginning with Julia v1.7.0 the default random number generator is the <code>Xoshiro</code> generator, which we initialize to an arbitrary, but reproducible, value.</p>
<p>The object returned by a call to <code>parametricbootstrap</code> has a somewhat complex internal structure to allow for the ability to simulate from complex models while still maintaining a comparatively small storage footprint. To examine the distribution of the parameter estimates we extract a table of all the estimated parameters and convert it to a <code>DataFrame</code>.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> hide_progress <span class="op">=</span> <span class="cn">true</span> <span class="co"># hide the progress bar when sampling</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="bu">Random</span>.<span class="fu">seed!</span>(<span class="fl">4321234</span>)      <span class="co"># random number generator</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>dsm01samp <span class="op">=</span> <span class="fu">parametricbootstrap</span>(<span class="fl">10_000</span>, dsm01; hide_progress)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>dsm01pars <span class="op">=</span> <span class="fu">DataFrame</span>(dsm01samp.allpars)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">first</span>(dsm01pars, <span class="fl">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div><div style="float: left;"><span>7×5 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">iter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">names</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">value</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1515.34</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">batch</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">10.1817</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">residual</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: right;">54.2804</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1502.81</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">batch</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">35.3983</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">residual</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: right;">48.3692</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1529.74</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">last</span>(dsm01pars, <span class="fl">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div><div style="float: left;"><span>7×5 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">iter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">names</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">value</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">9998</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">residual</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: right;">42.8227</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">9999</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1519.04</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">9999</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">batch</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">11.0336</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: right;">9999</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">residual</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: right;">58.4295</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: right;">10000</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1474.47</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: right;">10000</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">batch</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">23.4016</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: right;">10000</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">residual</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: right;">37.5372</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Plots of the bootstrap estimates for individual parameters are obtained by extracting subsets of the rows of this dataframe using <code>subset</code> methods from the <code>DataFrames</code> package or the <code>@subset</code> macro from the <code>DataFramesMacros</code> package. For example,</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>βdf <span class="op">=</span> <span class="pp">@subset</span>(dsm01pars, <span class="op">:</span><span class="kw">type</span> <span class="op">==</span> <span class="st">"β"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div><div style="float: left;"><span>10000×5 DataFrame</span></div><div style="float: right;"><span style="font-style: italic;">9975 rows omitted</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">iter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">names</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">value</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1515.34</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1502.81</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1529.74</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1537.34</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1516.77</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1522.16</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1523.27</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1527.52</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1518.53</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1538.92</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">11</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1518.34</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">12</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1537.79</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">13</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1533.77</td>
</tr>
<tr class="even">
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
<td style="text-align: right;">⋮</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9989</td>
<td style="text-align: right;">9989</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1542.72</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9990</td>
<td style="text-align: right;">9990</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1522.55</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9991</td>
<td style="text-align: right;">9991</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1517.65</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9992</td>
<td style="text-align: right;">9992</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1570.07</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9993</td>
<td style="text-align: right;">9993</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1531.39</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9994</td>
<td style="text-align: right;">9994</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1542.33</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9995</td>
<td style="text-align: right;">9995</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1513.89</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9996</td>
<td style="text-align: right;">9996</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1550.58</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9997</td>
<td style="text-align: right;">9997</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1517.84</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9998</td>
<td style="text-align: right;">9998</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1513.58</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9999</td>
<td style="text-align: right;">9999</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1519.04</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">10000</td>
<td style="text-align: right;">10000</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1474.47</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We begin by examining density plots constructed using the <a href="https://github.com/JuliaGraphics/AlgebraOfGraphics.jl">AlgebraOfGraphics</a> package. (In general we “fold” the code used to generate plots as it tends to have considerable detail that may distract from the plot itself. You can check the details by clicking on the “Code” button in the HTML version of the plot or in the quarto files on the <a href="https://github.com/JuliaMixedModels/EmbraceUncertainty">github repository</a> for this book.)</p>
<div class="cell" data-execution_count="30">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">draw</span>(</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data</span>(<span class="pp">@subset</span>(dsm01pars, <span class="op">:</span><span class="kw">type</span> <span class="op">==</span> <span class="st">"β"</span>)) <span class="op">*</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mapping</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>value <span class="op">=&gt;</span> <span class="st">"Bootstrap samples of β"</span>;</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>(<span class="op">:</span>names <span class="op">=&gt;</span> <span class="st">"Names"</span>),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="op">*</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  AoG.<span class="fu">density</span>();</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  figure<span class="op">=</span>(; resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">450</span>)),</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="31">
<div id="fig-dsm01_bs_beta_density" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-dsm01_bs_beta_density-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.3: Kernel density plot of bootstrap fixed-effects parameter estimates from dsm01</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find a way to use <code>:compact=true</code> when interpolating numeric values into the text</p>
</div>
</div>
<div class="cell" data-execution_count="31">
<div class="cell-output cell-output-display" data-execution_count="32">
<p>The distribution of the estimates of <code>β₁</code> is more-or-less a Gaussian (or “normal”) shape, with a mean value of 1528.021212 which is close to the estimated <code>β₁</code> of 1527.500000.</p>
<p>Similarly the standard deviation of the simulated β values, 17.711433258971017 is close to the standard error of the parameter, 17.694552727788437.</p>
</div>
</div>
<p>In other words, the estimator of the fixed-effects parameter in this case behaves as we would expect. The estimates are approximately normally distributed centered about the “true” parameter value with a standard deviation given by the standard error of the parameter.</p>
<p>The situation is different for the estimates of the standard deviation parameters, <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(\sigma_1\)</span>, as shown in <a href="#fig-dsm01_bs_sigma_density">Figure&nbsp;<span>1.4</span></a>.</p>
<div class="cell" data-execution_count="32">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">draw</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data</span>(<span class="pp">@subset</span>(dsm01pars, <span class="op">:</span><span class="kw">type</span> <span class="op">==</span> <span class="st">"σ"</span>)) <span class="op">*</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mapping</span>(</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>value <span class="op">=&gt;</span> <span class="st">"Bootstrap samples of σ"</span>;</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>(<span class="op">:</span>group <span class="op">=&gt;</span> <span class="st">"Group"</span>),</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="op">*</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  AoG.<span class="fu">density</span>();</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  figure<span class="op">=</span>(; resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">450</span>)),</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="33">
<div id="fig-dsm01_bs_sigma_density" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-dsm01_bs_sigma_density-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.4: Kernel density plot of bootstrap variance-component parameter estimates from model dsm01</figcaption>
</figure>
</div>
</div>
</div>
<p>The estimator for the residual standard deviation, <span class="math inline">\(\sigma\)</span>, is approximately normally distributed but the estimator for <span class="math inline">\(\sigma_1\)</span>, the standard deviation of the <code>batch</code> random effects is bimodal (i.e.&nbsp;has two “modes” or local maxima).</p>
<div class="cell" data-execution_count="33">
<div class="cell-output cell-output-display" data-execution_count="34">
<p>There is one peak around the “true” value for the simulation, 37.26034309083298, and another peak at zero.</p>
</div>
</div>
<p>The apparent distribution of the estimates of <span class="math inline">\(\sigma_1\)</span> in <a href="#fig-dsm01_bs_sigma_density">Figure&nbsp;<span>1.4</span></a> is being distorted by the method of approximating the density. A <a href="https://en.wikipedia.org/wiki/Kernel_density_estimation">kernel density estimate</a> approximates a probability density from a finite sample by blurring or smearing the positions of the sample values according to a <em>kernel</em> such as a narrow Gaussian distribution (see the linked article for details). In this case the distribution of the estimates is a combination of a continuous distribution and a spike or point mass at zero as shown in a histogram, <a href="#fig-dsm01_bs_sigma_hist">Figure&nbsp;<span>1.5</span></a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use a lower alpha in the colors for multiple histograms so the bars behind another color are more visible</p>
</div>
</div>
<div class="cell" data-execution_count="34">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">draw</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data</span>(<span class="pp">@subset</span>(dsm01pars, <span class="op">:</span><span class="kw">type</span> <span class="op">==</span> <span class="st">"σ"</span>)) <span class="op">*</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mapping</span>(</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>value <span class="op">=&gt;</span> <span class="st">"Bootstrap parameter estimates of σ"</span>;</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>(<span class="op">:</span>group <span class="op">=&gt;</span> <span class="st">"Group"</span>),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="op">*</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  AoG.<span class="fu">histogram</span>(; bins<span class="op">=</span><span class="fl">80</span>);</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  figure<span class="op">=</span>(; resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">450</span>)),</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="35">
<div id="fig-dsm01_bs_sigma_hist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-dsm01_bs_sigma_hist-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.5: Histogram of bootstrap variance-components as standard deviations from model dsm01</figcaption>
</figure>
</div>
</div>
</div>
<p>Nearly 1000 of the 10,000 bootstrap fits are “singular” in that one (or more) of the estimated unconditional distribution(s) of the random effects are degenerate. For this model the only way singularity can occur is for <span class="math inline">\(\sigma_1\)</span> to be zero.</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">countmap</span>(<span class="fu">issingular</span>(dsm01samp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>Dict{Bool, Int64} with 2 entries:
  0 =&gt; 9007
  1 =&gt; 993</code></pre>
</div>
</div>
<p>The distribution of the estimator of <span class="math inline">\(\sigma_1\)</span> with this point mass at zero is not at all like a Gaussian or normal distribution. This is why characterizing the uncertainty of these parameter estimates with a standard error is misleading. Quoting an estimate and a standard error for the estimate is only meaningful if these values adequately characterize the distribution of the values of the estimator.</p>
<p>In many cases standard errors are quoted for estimates of the variance components, <span class="math inline">\(\sigma_1^2\)</span> and <span class="math inline">\(\sigma^2\)</span>, whose distribution (<a href="#fig-dsm01_bs_sigmasqr_hist">Figure&nbsp;<span>1.6</span></a>) in the bootstrap sample is even less like a normal or Gaussian distribution than is the distribution of estimates of <span class="math inline">\(\sigma_1\)</span>.</p>
<div class="cell" data-execution_count="36">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">draw</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data</span>(<span class="pp">@transform</span>(<span class="pp">@subset</span>(dsm01pars, <span class="op">:</span><span class="kw">type</span> <span class="op">==</span> <span class="st">"σ"</span>), <span class="fu">abs2</span>(<span class="op">:</span>value))) <span class="op">*</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mapping</span>(</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>value_abs2 <span class="op">=&gt;</span> <span class="st">"Bootstrap sample of estimates of σ²"</span>,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=:</span>group,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="op">*</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  AoG.<span class="fu">histogram</span>(; bins<span class="op">=</span><span class="fl">200</span>);</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  figure<span class="op">=</span>(; resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">450</span>)),</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="37">
<div id="fig-dsm01_bs_sigmasqr_hist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-dsm01_bs_sigmasqr_hist-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.6: Histogram of bootstrap variance-components from model dsm01</figcaption>
</figure>
</div>
</div>
</div>
<p>The approach of creating coverage intervals from a bootstrap sample of parameter estimates, described in the next section, does accomodate non-normal distributions.</p>
<section id="sec-confints" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="sec-confints"><span class="header-section-number">1.5.1</span> Confidence intervals on the parameters</h3>
<p>A bootstrap sample of parameter estimates also provides us with a method of creating bootstrap coverage intervals, which can be regarded as confidence intervals on the parameters.</p>
<p>For, say, a 95% coverage interval based on 10,000 parameter estimates we determine an interval that contains 95% (9,500, in this case) of the estimated parameter values.</p>
<p>There are many such intervals. For example, from the sorted parameter values we could return the interval from the smallest up to the 9,500th largest, or from the second smallest up to the 9,501 largest, and so on.</p>
<p>The <code>shortestcovint</code> method returns the shortest of all these potential intervals which will correspond to the interval with the highest empirical density.</p>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">DataFrame</span>(<span class="fu">shortestcovint</span>(dsm01samp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<div><div style="float: left;"><span>3×5 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">names</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">lower</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">upper</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, String}">String?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">β</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1493.65</td>
<td style="text-align: right;">1563.5</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">batch</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">54.3061</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">σ</td>
<td style="text-align: left;">residual</td>
<td style="text-align: left; font-style: italic;">missing</td>
<td style="text-align: right;">35.3499</td>
<td style="text-align: right;">62.6078</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>For the <code>(Intercept)</code> fixed-effects parameter the interval is similar to an “asymptotic” or Wald interval constructed as the estimate plus or minus two standard errors.</p>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(<span class="fu">only</span>(dsm01.β) <span class="op">.+</span> [<span class="op">-</span><span class="fl">2</span>, <span class="fl">2</span>] <span class="op">*</span> <span class="fu">only</span>(dsm01.stderror))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1492.110894544422, 1562.8891054555756]</code></pre>
</div>
</div>
<p>The interval on the residual standard deviation, <span class="math inline">\(\sigma\)</span>, is reasonable, given that there are only 30 observations, but the interval of the standard deviation of the random effects, <span class="math inline">\(\sigma_1\)</span>, extends all the way down to zero.</p>
</section>
<section id="sec-dsm01trace" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="sec-dsm01trace"><span class="header-section-number">1.5.2</span> Tracking the progress of the iterations</h3>
<p>The optional argument, <code>thin=1</code>, in a call to <code>fit</code> causes all the values of <span class="math inline">\(\boldsymbol\theta\)</span> and the corresponding value of objective from the iterative optimization to be stored in the <code>optsum</code> property.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fix the recording of the fitlog so that the initial value is not recorded twice</p>
</div>
</div>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>dsm01trace <span class="op">=</span> <span class="fu">fit</span>(</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  MixedModel,</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="pp">@formula</span>(yield <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> (<span class="fl">1</span> <span class="op">|</span> batch)),</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  dyestuff;</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  thin<span class="op">=</span><span class="fl">1</span>,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">DataFrame</span>(dsm01trace.optsum.fitlog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<div><div style="float: left;"><span>18×2 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">2</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Vector{Float64}">Array…</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">[1.0]</td>
<td style="text-align: right;">327.767</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">[1.75]</td>
<td style="text-align: right;">331.036</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">[0.25]</td>
<td style="text-align: right;">330.646</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">[0.97619]</td>
<td style="text-align: right;">327.695</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">[0.928569]</td>
<td style="text-align: right;">327.566</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">[0.833327]</td>
<td style="text-align: right;">327.383</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: left;">[0.807188]</td>
<td style="text-align: right;">327.353</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">8</td>
<td style="text-align: left;">[0.799688]</td>
<td style="text-align: right;">327.347</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">9</td>
<td style="text-align: left;">[0.792188]</td>
<td style="text-align: right;">327.341</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">10</td>
<td style="text-align: left;">[0.777188]</td>
<td style="text-align: right;">327.333</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">11</td>
<td style="text-align: left;">[0.747188]</td>
<td style="text-align: right;">327.327</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">12</td>
<td style="text-align: left;">[0.739688]</td>
<td style="text-align: right;">327.329</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">13</td>
<td style="text-align: left;">[0.752777]</td>
<td style="text-align: right;">327.327</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">14</td>
<td style="text-align: left;">[0.753527]</td>
<td style="text-align: right;">327.327</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">15</td>
<td style="text-align: left;">[0.752584]</td>
<td style="text-align: right;">327.327</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">16</td>
<td style="text-align: left;">[0.752509]</td>
<td style="text-align: right;">327.327</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">17</td>
<td style="text-align: left;">[0.752591]</td>
<td style="text-align: right;">327.327</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">18</td>
<td style="text-align: left;">[0.752581]</td>
<td style="text-align: right;">327.327</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="40">
<div class="cell-output cell-output-display" data-execution_count="41">
<p>Here the algorithm converges after 18 function evaluations to a profiled deviance of 327.327059881143 at θ = 0.7525806394967323.</p>
</div>
</div>
</section>
</section>
<section id="sec-assessRE" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="sec-assessRE"><span class="header-section-number">1.6</span> Assessing the random effects</h2>
<p>What are sometimes called the BLUPs (or best linear unbiased predictors) of the random effects, <span class="math inline">\({\mathcal{B}}\)</span>, are the mode (location of the maximum probability density) of the conditional distribution, <span class="math inline">\(({\mathcal{B}}|{\mathcal{Y}}={\mathbf{y}})\)</span>, evaluated at the parameter estimates and the observed response vector, <span class="math inline">\({\mathbf{y}}\)</span>. Although BLUP is an appealing acronym, we don’t find the term particularly instructive (what is a “linear unbiased predictor” and in what sense are these the “best”?) and prefer the term “conditional mode” to describe this value.</p>
<p>These values are often considered as some sort of “estimates” of the random effects. It can be helpful to think of them this way but it can also be misleading. As we have stated, the random effects are not, strictly speaking, parameters — they are unobserved random variables. We don’t estimate the random effects in the same sense that we estimate parameters. Instead, we consider the conditional distribution of <span class="math inline">\({\mathcal{B}}\)</span> given the observed data, <span class="math inline">\(({\mathcal{B}}|{\mathcal{Y}}={\mathbf{y}})\)</span>.</p>
<p>Because the unconditional distribution, <span class="math inline">\({\mathcal{B}}\sim{\mathcal{N}}(\mathbf{0},\Sigma_\theta)\)</span> is continuous, the conditional distribution, <span class="math inline">\(({\mathcal{B}}|{\mathcal{Y}}={\mathbf{y}})\)</span> will also be continuous. In general, the mode of a probability density is the point of maximum density, so the phrase “conditional mode” refers to the point at which this conditional density is maximized. Because this definition relates to the probability model, the values of the parameters are assumed to be known. In practice, of course, we don’t know the values of the parameters (if we did there would be no purpose in forming the parameter estimates), so we use the estimated values of the parameters to evaluate the conditional modes.</p>
<p>Those who are familiar with the multivariate Gaussian distribution may recognize that, because both <span class="math inline">\({\mathcal{B}}\)</span> and <span class="math inline">\(({\mathcal{Y}}|{\mathcal{B}}={\mathbf{b}})\)</span> are multivariate Gaussian, <span class="math inline">\(({\mathcal{B}}|{\mathcal{Y}}={\mathbf{y}})\)</span> will also be multivariate Gaussian and the conditional mode will also be the conditional mean of <span class="math inline">\({\mathcal{B}}\)</span>, given <span class="math inline">\({\mathcal{Y}}={\mathbf{y}}\)</span>. This is the case for a linear mixed model but it does not carry over to other forms of mixed models. In the general case all we can say about <span class="math inline">\(\tilde{{\mathbf{b}}}\)</span> is that they maximize a conditional density, which is why we use the term “conditional mode” to describe these values. We will only use the term “conditional mean” and the symbol, <span class="math inline">\({\boldsymbol{\mu}}\)</span>, in reference to <span class="math inline">\(\mathrm{E}({\mathcal{Y}}|{\mathcal{B}}={\mathbf{b}})\)</span>, which is the conditional mean of <span class="math inline">\({\mathcal{Y}}\)</span> given <span class="math inline">\({\mathcal{B}}\)</span>, and an important part of the formulation of all types of mixed-effects models.</p>
<p>The conditional modes are available as a vector of matrices</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">only</span>(dsm01.b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>1×6 Matrix{Float64}:
 -16.6282  0.369516  26.9747  -21.8014  53.5798  -42.4943</code></pre>
</div>
</div>
<p>In this case the vector consists of a single matrix because there is only one random-effects term, <code>(1|batch)</code>, in the model and, hence, only one grouping factor, <code>batch</code>, for the random effects. There is only one row in the matrix because the random-effects term, <code>(1|batch)</code>, is a simple, scalar term.</p>
<p>To make this more explicit, random-effects terms in the model formula are those that contain the vertical bar (<code>|</code>) character. The variable or expression on the right of the <code>|</code> is the grouping factor for the random effects generated by this term. If the expression on the left of the vertical bar is <code>1</code>, as it is here, we describe the term as a <em>simple, scalar, random-effects term</em>. The designation “scalar” means there will be exactly one random effect generated for each level of the grouping factor. A simple, scalar term generates a block of indicator columns — the indicators for the grouping factor — in <span class="math inline">\({\mathbf{Z}}\)</span>. Because there is only one random-effects term in this model and because that term is a simple, scalar term, the model matrix <span class="math inline">\({\mathbf{Z}}\)</span> for this model is the indicator matrix for the levels of <code>batch</code>, as shown earlier in this section.</p>
<p>In the next chapter we fit models with multiple simple, scalar terms and, in subsequent chapters, we extend random-effects terms beyond simple, scalar terms. When we have only simple, scalar terms in the model, each term has a unique grouping factor and the elements of the list returned by can be considered as associated with terms or with grouping factors. In more complex models a particular grouping factor may occur in more than one term. In such cases the terms associated with the same grouping factor are internally amalgamated into a single term. Thus internally the random effects are associated with grouping factors, not the terms in the model formula.</p>
<p>Given the data, <span class="math inline">\({\mathbf{y}}\)</span>, and the parameter estimates, we can evaluate a measure of the dispersion of <span class="math inline">\(({\mathcal{B}}|{\mathcal{Y}}={\mathbf{y}})\)</span>. In the case of a linear mixed model, this is the conditional standard deviation, from which we can obtain a prediction interval. A plot of these prediction intervals is sometimes called a <em>caterpillar plot</em> because it can look like a fuzzy caterpillar when there are many levels of the grouping factor.</p>
<div class="cell" data-execution_count="42">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">caterpillar!</span>(</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Figure</span>(resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">250</span>)),</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ranefinfo</span>(dsm01, <span class="op">:</span>batch),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="43">
<div id="fig-caterpillar_dsm01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-caterpillar_dsm01-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.7: Caterpillar plot of prediction intervals for dsm01 random effects</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>caterpillar</code> function returns a plot with linear spacing of the levels on the y axis. An alternative</p>
<div class="cell" data-execution_count="43">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqcaterpillar!</span>(</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Figure</span>(resolution<span class="op">=</span>(<span class="fl">800</span>, <span class="fl">250</span>)),</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ranefinfo</span>(dsm01, <span class="op">:</span>batch),</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="44">
<div id="fig-qqcaterpillar_dsm01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="intro_files/figure-html/fig-qqcaterpillar_dsm01-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1.8: Quantile caterpillar plot of prediction intervals for dsm01 random effects</figcaption>
</figure>
</div>
</div>
</div>
<p>returns a plot where the intervals are plotted with vertical spacing corresponding to the quantiles of the standard normal distribution.</p>
<p>The <code>caterpillar</code> plot is preferred when there are only a few levels of the grouping factor, as in this case. When there are hundreds or thousands of random effects the <code>qqcaterpillar</code> form is preferred because it focuses attention on the “important few” at the extremes and de-emphasizes the “trivial many” that are close to zero.</p>
</section>
<section id="sec-stylistic" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="sec-stylistic"><span class="header-section-number">1.7</span> Some stylistic conventions</h2>
<p>To make it easier to recognize the form of the many models that will be fit in this book, we will adopt certain conventions regarding the argument specifications. In particular we will establish the convention of specifying <code>contrasts</code> for any categorical covariates and the possibility of using certain transformations, such as centering and scaling, of numeric covariates.</p>
<p>The name <code>contrasts</code> is used in a general sense here to specify certain transformations that are to take place during the process of converting a formula and the structure, or <a href="https://en.wikipedia.org/wiki/Database_schema">schema</a>, of the data into model matrices.</p>
<p>The <a href="https://github.com/JuliaStats/StatsModels.jl">StatsModels.jl package</a> allows for contrasts to be specified as a key-value dictionary where the keys are symbols and the values are of a type that specializes <code>StatsModels.AbstractContrasts</code>. The <a href="https://github.com/JuliaStats/MixedModels.jl">MixedModels.jl package</a> provides for a <code>Grouping()</code> contrast and the <a href="https://github.com/beacon-biosignals/StandardizedPredictors.jl">StandardizedPredictors.jl package</a> allows transformations to be expressed as contrasts.</p>
<p>For models <code>dsm01</code> and <code>dsm02</code> the only covariate in the model formula is <code>batch</code>, which is a grouping factor for the random effects. Thus the desired contrasts specification is</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>contrasts <span class="op">=</span> <span class="fu">Dict</span>(<span class="op">:</span>batch <span class="op">=&gt;</span> <span class="fu">Grouping</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(Symbols in Julia can be written as a colon followed by the name of the symbol. The colon creates an expression but, if the expression consists of a single name, then the expression is the symbol.)</p>
<p>It is best to get into the habit of specifying <code>Grouping()</code> contrasts for any grouping factors in the data. Doing so is not terribly important when the number of levels of the grouping factor is small, as in the examples in this chapter. However, when the number of levels is large, as for some of the models in later chapters, failure to specify <code>Grouping()</code> contrasts can cause memory faults when constructing the numeric represention of the model.</p>
<p>There is an advantage in assigning the contrasts dictionary to the name <code>contrasts</code> because a call to <code>fit</code> with the optional, named argument <code>contrasts</code></p>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>dsm01 <span class="op">=</span> <span class="fu">fit</span>(</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  MixedModel,</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="pp">@formula</span>(yield <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> (<span class="fl">1</span> <span class="op">|</span> batch)),</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  dyestuff;</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  contrasts<span class="op">=</span>contrasts,</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>can be condensed to</p>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>dsm01 <span class="op">=</span> <span class="fu">fit</span>(</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  MixedModel,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="pp">@formula</span>(yield <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> (<span class="fl">1</span> <span class="op">|</span> batch)),</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  dyestuff;</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  contrasts,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>That is, if the name of the object to be passed as a named argument is the same as the name of the argument, like <code>contrasts=contrasts</code>, then the name does not need to be repeated. Note that the comma after the positional arguments must be changed to a semicolon in this convention. This is necessary because it indicates that arguments following the semicolon are named arguments, not positional.</p>
<p>Another convention we will use is assigning the formula separately from the call to <code>fit</code> as part of a <code>let</code> block. Often the formula can become rather long, sometimes needing multiple lines in the call, and it becomes difficult to keep track of the other arguments. Assigning the formula separately helps in keeping track of the arguments to <code>fit</code>.</p>
<p>A <code>let</code> block is a way of making temporary assignments that do not affect the global state. An assignment to a variable name inside a <code>let</code> block is local to the block.</p>
<p>Thus <code>dsm01</code> can be assigned as</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>dsm01 <span class="op">=</span> <span class="kw">let</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  form <span class="op">=</span> <span class="pp">@formula</span>(yield <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> (<span class="fl">1</span> <span class="op">|</span> batch))</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(MixedModel, form, dyestuff; contrasts)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-ChIntroSummary" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="sec-ChIntroSummary"><span class="header-section-number">1.8</span> Chapter summary</h2>
<p>A considerable amount of material has been presented in this chapter, especially considering the word “simple” in its title (it’s the model that is simple, not the material). A summary may be in order.</p>
<p>A mixed-effects model incorporates fixed-effects parameters and random effects, which are unobserved random variables, <span class="math inline">\({\mathcal{B}}\)</span>. In a linear mixed model, both the unconditional distribution of <span class="math inline">\({\mathcal{B}}\)</span> and the conditional distribution, <span class="math inline">\(({\mathcal{Y}}|{\mathcal{B}}={\mathbf{b}})\)</span>, are multivariate Gaussian distributions. Furthermore, this conditional distribution is a spherical Gaussian with mean, <span class="math inline">\({\boldsymbol{\mu}}\)</span>, determined by the linear predictor, <span class="math inline">\({\mathbf{Z}}{\mathbf{b}}+{\mathbf{X}}{\boldsymbol{\beta}}\)</span>. That is, <span class="math display">\[
({\mathcal{Y}}|{\mathcal{B}}={\mathbf{b}})\sim
{\mathcal{N}}({\mathbf{Z}}{\mathbf{b}}+{\mathbf{X}}{\boldsymbol{\beta}}, \sigma^2{\mathbf{I}}_n) .
\]</span> The unconditional distribution of <span class="math inline">\({\mathcal{B}}\)</span> has mean <span class="math inline">\(\mathbf{0}\)</span> and a parameterized <span class="math inline">\(q\times q\)</span> variance-covariance matrix, <span class="math inline">\(\Sigma_\theta\)</span>.</p>
<p>In the models we considered in this chapter, <span class="math inline">\(\Sigma_\theta\)</span>, is a scalar multiple of the identity matrix, <span class="math inline">\({\mathbf{I}}_6\)</span>. This matrix is always a multiple of the identity in models with just one random-effects term that is a simple, scalar term. The reason for introducing all the machinery that we did is to allow for more general model specifications.</p>
<p>The maximum likelihood estimates of the parameters are obtained by minimizing the deviance. For linear mixed models we can minimize the profiled deviance, which is a function of <span class="math inline">\({\boldsymbol{\theta}}\)</span> only, thereby considerably simplifying the optimization problem.</p>
<p>To assess the precision of the parameter estimates we use a parametric bootstrap sample, when feasible. Re-fitting a simple model, such as those shown in this chapter, to a randomly generated response vector is quite fast and it is reasonable to work with bootstrap samples of tens of thousands of replicates. With larger data sets and more complex models, large bootstrap samples of parameter estimates could take much longer.</p>
<p>Prediction intervals from the conditional distribution of the random effects, given the observed data, allow us to assess the precision of the random effects.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="list" style="display: none">
<div id="ref-box73:_bayes_infer_statis_analy" class="csl-entry" role="listitem">
Box, G. E. P., &amp; Tiao, G. C. (1973). <em>Bayesian inference in statistical analysis</em>. Addison-Wesley.
</div>
<div id="ref-DanischKrumbiegel2021" class="csl-entry" role="listitem">
Danisch, S., &amp; Krumbiegel, J. (2021). Makie.jl: Flexible high-performance data visualization for julia. <em>Journal of Open Source Software</em>, <em>6</em>(65), 3349. <a href="https://doi.org/10.21105/joss.03349">https://doi.org/10.21105/joss.03349</a>
</div>
<div id="ref-davies72:_statis_method_in_resear_and_produc" class="csl-entry" role="listitem">
Davies, O. L., &amp; Goldsmith, P. L. (Eds.). (1972). <em>Statistical methods in research and production</em> (4th ed.). Hafner.
</div>
<div id="ref-saka:ishi:kita:1986" class="csl-entry" role="listitem">
Sakamoto, Y., Ishiguro, M., &amp; Kitagawa, G. (1986). <em>Akaike information criterion statistics</em> (p. 290). Reidel.
</div>
<div id="ref-schw:1978" class="csl-entry" role="listitem">
Schwarz, G. (1978). Estimating the dimension of a model. <em>Annals of Statistics</em>, <em>6</em>, 461–464.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./multiple.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Models With Multiple Random-effects Terms</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>